version: 0.2

phases:
  install:
    commands:
      # - npm i npm@latest -g
      - pip install --upgrade pip
      - pip install --upgrade awscli
    pre_build:
      commands:
        - npm install
    build:
      commands:
        - npm run build
    post_build:
      commands:
        - echo Deplot to S3 Bucket
        - aws s3 cp ./build s3://prod-e-commerce-0111/
