version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade pip
      - pip install --upgrade awscli
    pre_build:
      commands:
        - npm install
    build:
      commands:
        - npm run build
    post_build:
      commands:
        - aws s3 sync  ./build s3://profile.nylesdev.com/
